# BUSINESS INSIGHT QUESTIONS

# Q 1. WHICH CATEGORY GENERATE HIGEST REVENUE.
select
category,
ROUND(SUM(purchase_amount),2) AS highest_revenue
from customer_behaviour_analysis
group by category
order by highest_revenue desc;

-- BUSINESS PROBLEMS :- COMPANT DOES NOT KNOW WHICH CATEGORY CONTRIBUTE MOST TO REVENUE.
-- IMPACT :-- 
          # HELPS PRIORITIZE HIGH-PORFORMANCE CATEGORIES
          # OPTIMIZE INVENTORY PLANNING
          # IMPROVES MARKETING RIO

# Q 2. ARE DISCOUNT ACTUALLY INCREASING PURCHASE VALUE
SELECT 
      discount_applied,
      round(sum(purchase_amount),2) as total_revenue,
      round(avg(purchase_amount),2) as total_revenue
      from customer_behaviour_analysis
      group by discount_applied;
           
# BUSINES PROBLEM :-  Discount may reduce profit without increseing sales.

# IMPACT :-
         # IDENTIFY EFFECTIVENESS OF DISCOUNTS
         # REDUCE UNNECESSARY DISCOUNT COST.
         # Improve profit margines

# Q 3. WHAT IS THE REVANUE GENERATED BY MALE AND FEMAIL CUSTOMER

select
gender,
ROUND(SUM(purchase_amount),2) AS highest_revenue
from customer_behaviour_analysis
group by gender
order by highest_revenue desc;

# Q 4. WHICH CUSTOMER USED A DISCOUNT BUT STILL SPENT MORE THAN THE AVERAGE PURCHAGE AMOUNT.
SELECT 
    customer_id,
    purchase_amount,
    discount_applied
FROM customer_behaviour_analysis
where discount_applied="Yes" AND purchase_amount > (SELECT AVG(purchase_amount) from customer_behaviour_analysis);    
    
# Q 5. WHICH ARE THE TOP/BUTTOM 5 PRODUCTS WITH THE HIGEST AVERAGE REVIEW RATING.

SELECT 
     item_purchased,
     ROUND(AVG(review_rating),2) as Avg_ratings
     from customer_behaviour_analysis
     group by item_purchased
     order by Avg_ratings desc;
         
SELECT 
     item_purchased,
     ROUND(AVG(review_rating),2) as Avg_ratings
     from customer_behaviour_analysis
     group by item_purchased
     order by Avg_ratings asc;
     
     
# Q 6.  Average purchase : STANDARD VS EXPRESS SHIPPING

SELECT 
     shipping_type,
     COUNT(DISTINCT customer_id) as order_placed,
     round(avg(purchase_amount),2) as avg_purchase
from customer_behaviour_analysis
where shipping_type IN ("Standard","Express")
group by shipping_type;     
     
# Q 7.  DO SUBSCRIBED CUSTOMERS SPEND MORE COMPARE AVARAGE  SPEED AND TOTAL REVENUE BETWEEN SUBSCRIBERS AND NON-SUABSCRIBERS

SELECT 
     subscription_status,
     COUNT(customer_id) as users,
     round(avg(purchase_amount),2) as avg_revenue,
     round(sum(purchase_amount),2) as total_revenue
from customer_behaviour_analysis
group by subscription_status
order by total_revenue;     


# Q 8. 	TOP 5 PRODUCTS WITH HIGEST DISCOUNT USAGE %
SELECT
      item_purchased,
      count(item_purchased) as total_of_time_sold,
      COUNT(CASE WHEN discount_applied="yes" THEN 1 END) AS Number_of_time_sold_when_discount_applied,
		
      COUNT(CASE WHEN discount_applied="yes" THEN 1 END)*100.0/COUNT(*) AS discount_percent
      from customer_behaviour_analysis
      group by item_purchased
      order by discount_percent DESC;
      
# Q 9. SEGMENT CUSTOMER INTO NEW,RETURINING AND LOYAL BASED ON THEAIR TOTAL NUMBER OF PREVIOUS PURCHASE AND SHOW THE COUNT OF EACH SEGMENT      
 
 SELECT 
       CASE
          WHEN previous_purchases="0" THEN "NEW Customer"
           WHEN previous_purchases BETWEEN 1 AND 15 THEN "Returning Customer"
       ELSE "Loyal Customers"
END AS customer_segment,
COUNT(*) AS customer_count
FROM customer_behaviour_analysis
GROUP BY  CASE
          WHEN previous_purchases="0" THEN "NEW Customer"
           WHEN previous_purchases BETWEEN 1 AND 15 THEN "Returning Customer"
       ELSE "Loyal Customers"
END;
       
          

    
         
         
         
